
module foo
{
    module bar {

        typedef sequence < string > strings;

        struct Customer {
            long id;
            string name;
            string address;
        };

        module v3 {


            interface Messaging
            {
                Customer loadCustomer(in string id);
                string writeMessage(in string a1);
                string writeMessages(in strings a1);
                strings arryfy(in string a1, in long a2);
            };
        };

        module v4 {

            interface Messaging
            {
                Customer loadCustomer(in string id);
                string writeMessage(in string a1);
                string writeMessages(in strings a1);
                strings arryfy(in string a1, in long a2);
                strings closeMessages(in string a1);
            };
        };

    };
};
